### ISSUE TITLE
[REQ] Per-device selection

### ISSUE THREAD

**Issue by MarcoRavich** [kamrullab/Windows-Auto-Update-Manager#1]
Hi there,
I recently have issues with my Dell Optiplex 3000 integrated audio by Realtek: it refuses to play with vendor drivers but works with default (Microsoft) ones.
Solved - of course - by inhibiting the relative driver update, I found this interesting script @tenforums for easily do it: https://www.tenforums.com/tutorials/146562-prevent-windows-update-updating-specific-device-driver.html

It would be really useful to have a per-device (graphical) blocker, IMHO.

Hope that inspires.

**Comment by kamrullab** [comment]
Hi **MarcoRavich**,

Thanks for sharing your solution and the link! It’s really helpful to know that **blocking specific driver updates** can resolve compatibility issues with Realtek audio. I totally agree—a **per-device graphical blocker** would definitely be useful. It would give users more control over updates and prevent these kinds of conflicts. **Appreciate the inspiration!**
